### ISSUE TITLE
indicate the state of server-connection

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#18]
indicate warning on not-saved states
display success on every successful save

**Comment by freegyes** [comment]
this is rather for user xp only: display a 'saving changes' indicator on every keyup event for 3 seconds aand then display a 'all changes saved to server' notification.

**Comment by aedm** [comment]
Later. :)

**Comment by freegyes** [comment]
for inspiration: ![screen shot 2015-12-02 at 11 26 44](https://cloud.githubusercontent.com/assets/4889889/11528531/ac7f0cec-98e7-11e5-8d6f-3207fd39e895.png)

**Comment by aedm** [comment]
![image](https://cloud.githubusercontent.com/assets/7765984/11610774/8ce74198-9bac-11e5-835e-c8912d4dfb10.png)

Dunno if it's okay, I don't really understand what "Saved 0" means. PTAL.
