### ISSUE TITLE
have a 'Finish' button that triggers extra actions on the finishing screen

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#20]

**Comment by aedm** [comment]
What kind of actions?
I thought the "finish" button should be at the bottom of "the year ahead" screen.

Maybe we don't need a "finish" button at all, I think the "I believe" button could simply turn to the finishing screen.

**Comment by freegyes** [comment]
maybe you're right.

my basic idea was that these are two isolated actions that need completely different mindset.

I believe --> clicking this makes me think of all the answers I gave before and gives a strong positive push to look forward for the future.

finish --> the actual action that says 'now i'm ready to set these answers in stone'

bottom line: I think there should be two different objects, but you're right that they can be displayed on the same page.
