### ISSUE TITLE
have a 'share on...' section

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#22]
- facebook
- twitter
- instagram
- google plus
- linkedin
- pinterest
- reddit
- whatsapp

**Comment by aedm** [comment]
Do you happen to have example code at hand? :)

**Comment by freegyes** [comment]
not really. with a quick search I found [an example code snippet in php+js](http://www.jaredatchison.com/code/create-manual-social-media-share-buttons/):

in our case a very similar solution to this should make it. :)

**Comment by freegyes** [comment]
maybe this meteor package?
[shareIt](https://atmospherejs.com/lovetostrike/shareit)

```
ShareIt.configure({
    sites: {
        'facebook': {
            'appId': 171485476532772
        },
        'twitter': {},
        'googleplus': {},
        'pinterest': {}
    }
```

**Comment by aedm** [comment]
This package doesn't work for some reason. :-/
I could probably add these manually faster than debugging the package.

**Comment by aedm** [comment]
Sharing on Instagram from a webapp is not supported on purpose.
See http://stackoverflow.com/questions/17673156/instagram-share-photo-from-webpage
