### ISSUE TITLE
have third party auth enabled

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#29]
for
- [facebook](https://atmospherejs.com/meteor/accounts-facebook)
- [google](https://atmospherejs.com/meteor/accounts-google)
- [twitter](https://atmospherejs.com/meteor/accounts-twitter)

and remove the option of signing in with a user name (we need the email address)

**Comment by aedm** [comment]
"we need the email address" -- I removed it, but some folks are not comfortable with disclosing their real email addresses, and I think they should have the right to their opinion.
