### ISSUE TITLE
convert asterisk(*)-comments to a screen-friendly form

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#42]
tooltip or a popover of some kind?

**Comment by freegyes** [comment]
- in the following areas*
- Bucket List **
- Do good for yourself and forgive.*
- A book was made about your past year*

**Comment by aedm** [comment]
I believe tooltips and popovers are outright unfriendly for such a simple case. The most friendly form would be good phrasing IMO. These lines of text don't really need to be separate, even when printed.

**Comment by freegyes** [comment]
They are written and to be read in a more informal tone. That's why they were separated in the booklet. They contain no cardinal information and as such IMO they have no place in the more formal questions that tend to be concise.

**Comment by aedm** [comment]
I really think making the user click/tap one more just to read a question is bad UX. There's no need for that. 
Also if these comments are there, then the text is just as complex then, but in a more complicated structure. These comments aren't explaining anything (except the bucket list), they are actually part of the description. I don't think a footnote is a good tool for this purpose, but a popover is even worse.

**Comment by freegyes** [comment]
compromised: omit asterisk-comments
