### ISSUE TITLE
update YC logo

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#45]
change for a higher quality, borderless one from here:
https://github.com/freegyes/YearCompass/tree/master/assets/img

(this issue will recieve a ping when new image exists)

**Comment by aedm** [comment]
Please explain. I think the logo is high resolution already and has no borders.
(Assign it back on me when there's something I can do.)

**Comment by freegyes** [comment]
it does have a border. :)

![screen shot 2015-12-06 at 21 57 18](https://cloud.githubusercontent.com/assets/4889889/11615552/8cc3d86c-9c64-11e5-88c5-a48cca80441e.png)

**Comment by freegyes** [comment]
![logo_img_with_text_right_750x150](https://cloud.githubusercontent.com/assets/4889889/11640710/609e4076-9d34-11e5-8449-ffc7e2c5c4ef.png)

from here:
https://github.com/freegyes/YearCompass/blob/master/assets/img/dist/logos/logo_img_with_text_right_750x150.png
