### ISSUE TITLE
make user typed text stand out

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#52]
make it not black (maybe blue) and maybe render with a default typeface?

**Comment by aedm** [comment]
I don't get the "default typeface" thing. Do you want to use a third font for the answers?
Will make it blue though.

**Comment by freegyes** [comment]
"3 percet lamentáltam rajta, hogy zavar-e a 
  kék kurzor és betű a szövegdobozokban. 
  mérlegelvén az ellenérveket is (kevésbé 
  különül el a dobozon belüli és kívüli szöveg), 
  a válaszom igen. jobb lenne, ha fekete lenne 
  a beírt szöveg. vagy kompromisszumos 
  megoldásként választhasson a user."
