### ISSUE TITLE
setup social share predefined content

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#65]
the default messages should be defined

**Comment by freegyes** [comment]
Facebook - T0204
Twitter - T0205
Pinterest - T0206
Google+ - T0207
Reddit - T0208
Linkedin - T0209
Whatsapp - T0209

**Comment by aedm** [comment]
Google+, Reddit and LinkedIn don't support custom texts in the share URL.

**Comment by aedm** [comment]
Neither does Facebook. :)
