### ISSUE TITLE
introduce a 'finish' button on the finish screen

### ISSUE THREAD

**Issue by freegyes** [aedm/yearcompass#66]
clicking that displaya a you are now done message => { this.text("T0164") } and shortly after that redirects to the base yc.com site (timeout 5000)

**Comment by freegyes** [comment]
{ this.text("T0214") }  // Take me to YearCompass.com

**Comment by aedm** [comment]
Maybe I don't get the idea, but it's a simple link on the finish page.

**Comment by aedm** [comment]
Wrong URL.

**Comment by aedm** [comment]
This has already been fixed.
