### ISSUE TITLE
Display a flag next to the user profile picture.

### ISSUE THREAD

**Issue by aedm** [aedm/yearcompass#72]
Based on user feedback.

„- én szívesen olvasnám mindezt magyarul"
„bejelentkezés után az első oldal (esernyős) már nem volt elérhető, kerestem, mert talán ott mulasztottam el valamit a nyelvválasztással kapcsolatban
ha mégsem, akkor lehet, hogy oda érdemes lenne valamit írni erről vagy valahogyan jobban felhívni rá figyelmet"

**Comment by freegyes** [comment]
"Bejelentkezés után ha nyelvet szeretnék váltani, akkor nem triviális, hogy a profilomra kellene mennem. (lehetne egy külön Nyelvet váltok gomb)"

**Comment by freegyes** [comment]
"jobb fent a nyelvválasztónál a bejelentkező 
  oldalt kivéve csak egy üres szürke háromszöget 
  látok. jobb lenne, ha látnám a zászlómat."

**Comment by freegyes** [comment]
"A bejelentkezés után a "user menu" ugyanaz lesz mint a korábbi nyelv választó menü, látom emögött a döntés mögött is a racionalitást, mégis nekem földi felhasználónak fura volt, hogy látszólag eltűnt a egy korábban meglévő funkcionalitás. Ez azért érdekes mert nem látom, melyik nyelv van kiválasztva, ami viszont releváns kérdés, mert nem mindig vannak lefordítva a szövegek és néha az angolul látszanak."
